require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/initializers/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1.1
Layout/ClassStructure:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Max: 120
Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 500
Metrics/ModuleLength:
  Max: 500
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
