server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # React SPA
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Rails API — real IP from Cloudflare header
  location /api/ {
    proxy_pass http://api:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $http_cf_connecting_ip;
    proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
    proxy_set_header X-Forwarded-Proto https;
  }
}
