linters:
  ClassesBeforeIds:
    EnforcedStyle: 'id'
  LineLength:
    max: 120
  # RuboCop:
  #   ignored_cops:
  #     - Style/UnneededInterpolation
  #     - Lint/BlockAlignment
  #     - Lint/EndAlignment
  #     - Lint/Void
  #     - Layout/AlignParameters
  #     - Layout/IndentationWidth
  #     - Layout/TrailingBlankLines
  #     - Layout/TrailingWhitespace
  #     - Metrics/BlockLength
  #     - Metrics/LineLength
  #     - Style/BlockNesting
  #     - Style/ElseAlignment
  #     - Style/EndOfLine
  #     - Style/FileName
  #     - Style/FinalNewline
  #     - Style/FrozenStringLiteralComment
  #     - Style/IfUnlessModifier
  #     - Style/Next
  #     - Style/WhileUntilModifier
